# SVM

In [1]:
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import seaborn as sns

# ------KFOLDS-----------

In [ ]:
datos = pd.read_csv('svm.csv')
df = pd.DataFrame(datos)

X1 = df['X1']
X2 = df['X2']

kf = KFold(n_splits=10)

i = 1
for valx,valy in kf.split(X1):
    df.iloc[valx].to_csv('train'+str(i)+".csv",index=False)
    df.iloc[valy].to_csv('test'+str(i)+".csv",index=False)
    i=i+1
#     print(valx,valy)
#     print("Entrenamiento:\n",df.iloc[valx])
#     print("Prueba:\n",df.iloc[valy])


# --------------------------

In [39]:
svmtxt = open('SVM.txt','w')
calcular = []
SVM = SVC(kernel = 'linear',C=10)

svmtxt.write("Angelo Aldo Perez Rodriguez\n")
svmtxt.write("Algoritmo Support Vector Machine\n")

for j in range(1,11):
    train = pd.read_csv('train'+str(j)+'.csv',header=0)
    test = pd.read_csv('test'+str(j)+'.csv',header=0)
    X_train = train.loc[:,train.columns !='Y']
    Y_train = train.Y
    SVM.fit(X_train,Y_train)
    
    #train
    x_min, x_max = train.X1.min() - .1, train.X1.max() + .1
    y_min, y_max = train.X2.min() - .1, train.X2.max() + .1
    h = .02
    xx,yy = np.meshgrid(np.arange(x_min,x_max,h), np.arange(y_min,y_max,h))
    Z = SVM.predict(np.c_[xx.ravel(),yy.ravel()])
    Z = Z.reshape(xx.shape)
    
    #test
    x_min, x_max = train.X1.min() - .1, train.X1.max() + .1
    y_min, y_max = train.X2.min() - .1, train.X2.max() + .1
    h = .02
    xx,yy = np.meshgrid(np.arange(x_min,x_max,h), np.arange(y_min,y_max,h))
    Z = SVM.predict(np.c_[xx.ravel(),yy.ravel()])
    Z = Z.reshape(xx.shape)
    
    # ----------------
    X_test = test.loc[:,test.columns  !='Y']
    Y_test = test.Y
    pred = SVM.predict(X_test)
    print(pred)
    accuracy = accuracy_score(
            y_true = Y_test,
            y_pred = pred,
            normalize=True
            )
    print("La precision es:"+ str((100*accuracy))+"%")
    svmtxt.write("Tasa de clasificación del fold "+str(j)+" : "+str((100*accuracy))+"%\n")
    calcular.append(accuracy*100)

promedio = sum(calcular)/len(calcular)
calcularnp = np.array(calcular)
desviacion = math.sqrt(np.sum((calcularnp-promedio)**2)/len(calcular)-1)
svmtxt.write("\n\n")
svmtxt.write("Tasa de clasificación promedio: "+str(promedio)+"%\n")
svmtxt.write("Desviación estandar "+str(desviacion)+"\n")
svmtxt.close()

[1 1 0 0 0 0 0 1 0 1 1 0 0 1 1]
La precision es:80.0%
[1 1 1 1 1 1 0 1 0 1 1 0 0 0 0]
La precision es:80.0%
[0 0 0 1 1 0 0 1 0 0 0 1 1 0 1]
La precision es:86.66666666666667%
[0 0 0 1 1 1 1 0 0 1 0 1 1 1 0]
La precision es:86.66666666666667%
[1 1 1 0 1 0 0 1 1 1 0 0 0 0 1]
La precision es:80.0%
[1 0 1 1 1 0 1 1 0 0 0 1 0 0 0]
La precision es:93.33333333333333%
[1 0 0 0 1 0 1 1 0 1 0 0 1 1 0]
La precision es:93.33333333333333%
[0 1 1 0 0 0 0 0 1 0 1 0 0 0 0]
La precision es:93.33333333333333%
[1 0 1 1 1 1 0 1 0 1 0 0 1 0 1]
La precision es:66.66666666666666%
[1 1 0 1 0 0 0 0 0 1 1 0 1 0 0]
La precision es:86.66666666666667%
